services:
  _defaults:
    autoconfigure: true
    autowire: true

  StudentCorner\Shared\Infrastructure\Symfony\SessionAuthMiddleware:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
