version: '3.1'

services:
  student_corner.mysql:
    image: mysql:5.7
    #restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: useruser
      MYSQL_ROOT_PASSWORD: rootroot
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./var/StudentCorner/Mysql:/var/lib/mysql

  shared.rabbitmq:
    image: rabbitmq:3-management
    hostname: shared
    environment:
      #RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    expose:
      - 15672
    volumes:
      #- ./src/Shared/Infrastructure/Queue/RabbitMQ/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./var/Shared/RabbitMQ:/var/lib/rabbitmq
      #- ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
      #- ./autocluster-0.4.1.ez:/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.5/plugins/autocluster-0.4.1.ez

  shared.elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    ports:
      - 9200:9200
    volumes:
      - ./var/Shared/Elasticsearch:/usr/share/elasticsearch/data

  shared.kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://shared.elasticsearch:9200/
    ports:
      - 5601:5601
    depends_on:
      - shared.elasticsearch

  shared.mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

  student_corner.nginx:
    image: nginx:1.15-alpine
    ports:
      - 8030:80
    volumes:
      - .:/app:delegated
      - ./etc/infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - student_corner.php

  student_corner.php:
    build:
      context: ./etc/infrastructure
      dockerfile: php.Dockerfile
    ports:
      - 9090:9001
    volumes:
      - .:/app:delegated
    env_file:
      - .env
    depends_on:
      - student_corner.mysql
      - shared.rabbitmq

  shared.supervisor:
    build:
      context: ./etc/infrastructure
      dockerfile: supervisor.Dockerfile
    ports:
      - 9091:9001
    volumes:
      - .:/app:delegated
    env_file:
      - .env
    depends_on:
      - student_corner.mysql
      - shared.rabbitmq
