services:
  _defaults:
    autoconfigure: true
    autowire: true

  StudentCornerWeb\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  StudentCornerWeb\Command\:
    resource: '../src/Command'
    tags: ['console.command']

  StudentCornerWeb\Command\RabbitMq\ConfigureCommand:
    arguments:
      - '@Shared\Infrastructure\Queue\RabbitMq\RabbitMqConfigurator'
      - '%env(RABBITMQ_EXCHANGE)%'
      - !tagged event.consumer
