framework:
  test: true

services:
  _defaults:
    autoconfigure: true
    autowire: true

  StudentTrackerWeb\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  StudentTracker\:
    resource: '../../../../../'

  Shared\:
    resource: '../../../../../Shared'